# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obbctl < Formula
  desc ""
  homepage "https://github.com/Onboardbase/ctl-releases"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Onboardbase/ctl-releases/releases/download/v0.0.1/obbctl_Darwin_arm64.tar.gz"
      sha256 "b3dbffda545aab5b6605c43968ec9560e304a49c41e98a34d52ffc9e6287080e"

      def install
        bin.install "obbctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/ctl-releases/releases/download/v0.0.1/obbctl_Darwin_x86_64.tar.gz"
      sha256 "3f7588793399e584a3bde88a9814394922b546233973db4e1bf8141594434894"

      def install
        bin.install "obbctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Onboardbase/ctl-releases/releases/download/v0.0.1/obbctl_Linux_arm64.tar.gz"
      sha256 "52d1fb4abdd5adaee0c0985ffaa4c032c1623fc7b8b8a4188d69072bb10d3fd4"

      def install
        bin.install "obbctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/ctl-releases/releases/download/v0.0.1/obbctl_Linux_x86_64.tar.gz"
      sha256 "940119e9730caed99f4a44c275e526b13c67cc1d1bca9a1905049f952a49166e"

      def install
        bin.install "obbctl"
      end
    end
  end
end
