# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obbctl < Formula
  desc ""
  homepage "https://github.com/Onboardbase/obbctl"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Onboardbase/obbctl/releases/download/v0.0.1/obbctl_Darwin_arm64.tar.gz"
      sha256 "bebf40f06c3f9b1e6bf9459079a986d6268dffe793ee771209e2ce9363f95d4c"

      def install
        bin.install "obbctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/obbctl/releases/download/v0.0.1/obbctl_Darwin_x86_64.tar.gz"
      sha256 "158da9a8949d4412f591ce5cad15e241653ecd470e6ab38bc45b06989099ae26"

      def install
        bin.install "obbctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Onboardbase/obbctl/releases/download/v0.0.1/obbctl_Linux_arm64.tar.gz"
      sha256 "7ffce2cc2e41e43201f20c440f076b1483fbc68c13c762c5a10014d3bc93733b"

      def install
        bin.install "obbctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Onboardbase/obbctl/releases/download/v0.0.1/obbctl_Linux_x86_64.tar.gz"
      sha256 "163bf54cc742a79d78aff40ce9f9cb488438c6b0c31d92a2162410299a650355"

      def install
        bin.install "obbctl"
      end
    end
  end
end
